// ============================================================
//  CONTACT — contact entity
// ============================================================

export interface Contact {
  id?: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null; // nullable — not required at signup
  color: string; // hex color for avatar circle
  initials: string; // generated from first_name + last_name
  auth_user_id?: string; // links to Supabase Auth user
}

// ============================================================
//  DTO
// ============================================================

// User fills the form — color/initials/auth_user_id generated by service
export type CreateContactDto = Omit<Contact, 'id' | 'auth_user_id' | 'initials' | 'color'>;

// Partial update — only fields user wants to change
export type UpdateContactDto = Partial<CreateContactDto>;

// Used during signup — includes color/initials generated on frontend, excludes id
export type UpsertContactDto = Omit<Contact, 'id'>;

export type ContactMode = 'add' | 'edit';
