// ============================================================
//  CONTACT — contact entity
// ============================================================

export interface Contact {
  id?: string;
  first_name: string;
  last_name: string;
  email: string;
  /** Nullable — not required at signup. */
  phone?: string | null;
  /** Hex color for the avatar circle, generated once at registration and persisted (see CLAUDE.md). */
  color: string;
  /** Generated from `first_name` + `last_name`. */
  initials: string;
  /** Links to the Supabase Auth user this contact was created for. */
  auth_user_id?: string;
}

// ============================================================
//  DTO
// ============================================================

/** Fields the user fills in via the form — `color`/`initials`/`auth_user_id` are generated by ContactService. */
export type CreateContactDto = Omit<Contact, 'id' | 'auth_user_id' | 'initials' | 'color'>;

/** Partial update — only the fields the user actually wants to change. */
export type UpdateContactDto = Partial<CreateContactDto>;

/** Used during signup — includes `color`/`initials` generated on the frontend, excludes `id`. */
export type UpsertContactDto = Omit<Contact, 'id'>;

export type ContactMode = 'add' | 'edit';
